### PR TITLE
Implement and test `GameBeatmapUsageCheck` and `MatchBeatmapCheck`

### LINKED ISSUE #449: Warning flags for `Match` and `Game`
Depends on #438

# Overview

This feature covers the implementation and testing of warning flags on `Match` and `Game`. These flags function similarly to that of the AutomatedChecks, except there is no automated rejection of this data. The data will end up being `PreVerified` should there only be flags and no other means of auto rejection.

The goal of this feature is to implement the following warning flags:

- `Match`
  - Title regex matching: `{T_ABR}: ({TEAM_A}) vs ({TEAM_B})` where `{T_ABR}` is the tournament's abbreviation. `vs` check should be loose and cover `VS` `vs.`, and everything in between (codified as `UnexpectedTitleFormat`).
  - Match game count is exactly 3 or 4 (codified as `LowGameCount`).
- `Game`
  - If a tournament does not have a stored mappool and the beatmap is used exactly once in the entire tournament (codified as `BeatmapUsedOnce`)
  - If a tournament does have a stored mappool, and the beatmap is not in the mappool, and the game is not one of the first two games in the match (codified as `BeatmapNotInMappool`)

# Tasks

- [x] #478
- [x] #479
- [x] #480

### LINKED ISSUE #479: Create `AutomationCheck`s that check for and apply `MatchWarningFlags` and `GameWarningFlags`
Depends on #478

Add support for the DataWorker to check for and apply `MatchWarningFlags` and `GameWarningFlags` during automation checks. Implement the following as implementations of `AutomationCheckBase<Match>` and `AutomationCheckBase<Game>` respectively.

- Matches
    - [x] Rename `MatchNameCheck` to `MatchNamePrefixCheck`
    - [x] Rename `MatchRejectionReason.InvalidName` to `MatchRejectionReason.NamePrefixMismatch`
    - [x] `MatchNameFormatCheck`: Check the title of the match against a regex (`{T_ABR}: ({TEAM_A}) vs ({TEAM_B})` where `{T_ABR}` is the tournament's abbreviation. `vs` check should be loose and cover `VS` `vs.`, and everything in between). Should it fail, apply `UnexpectedTitleFormat` to `Match.WarningFlags`.
    - [x] `MatchGameCountWarningCheck`: Check game count. If the game count is 3 or 4, apply `LowGameCount` to `Match.WarningFlags`.

- Games
    - [x] `GameBeatmapSingleUsageCheck`: If a tournament does not have a stored mappool and the beatmap is used exactly once in the entire tournament, apply `BeatmapUsedOnce` to `Game.WarningFlags`.
    - [x] `BeatmapNotPooled`: If a `Tournament`'s `PooledBeatmaps` collection does not contain the `Game`'s `Beatmap`, mark the `Game` as `Rejected` with a `RejectionReason` of `BeatmapNotPooled` 

- [x] Unit test all new automation checks

### PR DESCRIPTION
**Pull request by hburn7**
Closes #479 
Closes #449

Adds functionality for `GameBeatmapUsageCheck` and `MatchBeatmapCheck` automation workflows.

Game:
  - If a beatmap is played in a game but is not pooled (and the tournament has a PooledBeatmaps collection), reject the game with `BeatmapNotPooled`.
  - If a beatmap is played in a game and is in the tournament's PooledBeatmaps collection, it will not be rejected.
  - If a beatmap is used once throughout the entire tournament and the tournament does not have a known PooledBeatmaps collection, apply `GameWarningFlags.BeatmapUsedOnce`.

Match:
  - If a match's games collection features games beyond the first 2 in the collection with a `GameRejectionReason` of `BeatmapNotPooled`, apply `MatchWarningFlags.UnexpectedBeatmapsFound`.

### CODE REVIEW

**Comment by myssto** [comment]
cq and tests failing? LOL

**Comment by hburn7** [comment]
> cq and tests failing? LOL

It fails to build because it considers warnings as errors in CI

**Comment by hburn7** [comment]
actually no, there's just an error lol

**Review by myssto — APPROVED** [review]
It took me a minute to figure out what you did with the new rejection reason but I really like it! If I'm understanding it right, it allows all games to be flagged for beatmap usage regardless of their played position (1st, 2nd, 3rd, etc) but those warnings will only result in a rejecting when moving up to a match if they are 1st or 2nd correct?

Either way, really nice work!

**Comment by hburn7** [comment]
Update here when functional testing is done

**Comment by hburn7** [comment]
Seems to be working fine after functional testing.

**Pull request merged**
